release:
  draft: true

builds:
  - id: hobigon-api
    main: ./cmd/http
    binary: api
    goos:
      - linux
    goarch:
      - amd64

  - id: hobigon-cli
    main: ./cmd/cli
    binary: hobi
    goos:
      - linux
    goarch:
      - amd64

  - id: hobigon-graphql
    main: ./cmd/graphql
    binary: graphql-server
    goos:
      - linux
    goarch:
      - amd64
