settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
  - name: rest
    path: .
    commands:
      install:
        status: true
        method: make build target=api env=local
      run:
        status: true
        method: ./cmd/rest/bin/api-server
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .idea
        - logs
        - docker
  
  - name: graphql
    path: .
    commands:
      install:
        status: true
        method: make build target=graphql env=local
      run:
        status: true
        method: ./cmd/graphql/bin/graphql-server
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .idea
        - logs
        - docker
