name: Test

on:
  push:

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        env:
          APP_ENV: test
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          args: --timeout 5m0s

      - name: Slack success notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_USERNAME: Mario
          SLACK_ICON_EMOJI: ":mario:"
          SLACK_TITLE: Test Success

      - name: Slack failure notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_USERNAME: Mario
          SLACK_ICON_EMOJI: ":mario:"
          SLACK_COLOR: danger
          SLACK_TITLE: Test Failure

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: review
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - name: Build
        run: make build-all env=prd
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: 'cmd/rest/bin/api-server,cmd/cli/bin/hobi,cmd/graphql/bin/graphql-server'
          target: "api-server-golang"
      - name: Slack deploy success notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_51 }}
          SLACK_USERNAME: Mario
          SLACK_ICON_EMOJI: ':mario:'
          SLACK_TITLE: Deploy Success
      - name: Slack deploy failure notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_51 }}
          SLACK_USERNAME: Mario
          SLACK_ICON_EMOJI: ':mario:'
          SLACK_COLOR: danger
          SLACK_TITLE: Deploy Failure
