name: Workflow for Golang
on: [push]

jobs:
   test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - uses: ./
        - name: Lint
          uses: ./.github/actions/golang
        - name: Test
          run: go test ./...
