name: Test

on:
  push:
    branches:
      - master

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        env:
          APP_ENV: test
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          args: --timeout 5m0s

      - name: Slack success notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_USERNAME: Mario
          SLACK_ICON_EMOJI: ":mario:"
          SLACK_TITLE: Test Success

      - name: Slack failure notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_USERNAME: Mario
          SLACK_ICON_EMOJI: ":mario:"
          SLACK_COLOR: danger
          SLACK_TITLE: Test Failure
